# Generated by Django 4.2.30 on 2026-05-08 16:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('requires_followup', 'Requires Follow-up')], default='pending', max_length=20)),
                ('risk_score', models.FloatField(help_text='Numeric risk score from 0.0 (no risk) to 10.0 (critical).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], editable=False, max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('inspector', 'Lead Inspector'), ('analyst', 'Risk Analyst'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('position_x', models.FloatField(help_text='Horizontal position on floor plan (0–100%).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('position_y', models.FloatField(help_text='Vertical position on floor plan (0–100%).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='core.project')),
            ],
            options={
                'ordering': ['severity', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('critical', 'Critical'), ('completed', 'Completed')], default='open', max_length=20)),
                ('risk_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('key_findings', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.inspection')),
                ('lead_inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('risk_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_priorities', to='core.project')),
            ],
            options={
                'ordering': ['-risk_score', 'status'],
            },
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspection_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.project'),
        ),
        migrations.CreateModel(
            name='GeospatialZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(choices=[('fault_line', 'Fault Line'), ('liquefaction', 'Soil Liquefaction'), ('erosion', 'Erosion Risk'), ('flood', 'Flood Zone'), ('general', 'General Risk Zone')], max_length=30)),
                ('risk_level', models.CharField(choices=[('zone_a', 'Zone A — Critical'), ('zone_b', 'Zone B — Moderate'), ('zone_c', 'Zone C — Low')], max_length=20)),
                ('coordinates', models.JSONField(help_text='Array of [longitude, latitude] pairs forming a closed polygon.')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geospatial_zones', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_line_proximity', models.CharField(choices=[('none', 'None'), ('low', 'Low Proximity'), ('moderate', 'Moderate Proximity'), ('high', 'High Proximity'), ('very_high', 'Very High Proximity')], default='none', max_length=20)),
                ('soil_liquefaction_risk', models.CharField(choices=[('zone_a', 'Zone A — Critical'), ('zone_b', 'Zone B — Moderate'), ('zone_c', 'Zone C — Low'), ('none', 'None')], default='zone_c', max_length=20)),
                ('erosion_potential', models.CharField(choices=[('severe', 'Severe'), ('moderate', 'Moderate'), ('low', 'Low'), ('negligible', 'Negligible')], default='low', max_length=20)),
                ('overall_risk_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('additional_analysis', models.TextField(blank=True)),
                ('assessed_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_risk', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='DamageTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=20)),
                ('value', models.FloatField(help_text='Numeric damage severity value used for chart rendering.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_trends', to='core.project')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('project', 'date', 'severity')},
            },
        ),
    ]
